export const IMAGE_CACHE_KEY = "URLS_OF_IMAGES_TEMPORARILY_STORED";
export const IMAGE_CACHE_MAX_AGE = 12 * 60 * 60 * 1000;
export const IMAGE_CACHE_MAX_ITEMS = 300;
export const IMAGE_CACHE_PERSIST_DELAY = 500;
